import { useQuasar } from 'quasar';
import {
  mdiAlertCircle,
  mdiArrowDown,
  mdiArrowUp,
  mdiBookCog,
  mdiChevronLeft,
  mdiChevronRight,
  mdiFileDocumentPlus,
  mdiFilePdfBox,
  mdiFileStarFourPoints,
  mdiImageCheck,
  mdiImageCheckOutline,
  mdiMenuDown,
  mdiOctagramMinus,
  mdiOctagramMinusOutline,
  mdiOctagramPlus,
  mdiOctagramPlusOutline,
  mdiPageFirst,
  mdiPageLast,
  mdiPlay,
  mdiContentSavePlus,
  mdiUndo,
  mdiRedo,
  mdiRepeatVariant,
  mdiSwapVertical,
  mdiFormatParagraph,
  mdiTrashCan,
  mdiPlus,
  mdiClose,
  mdiReload,
  mdiAlphaCCircleOutline,
  mdiViewList,
  mdiTable,
  mdiSyncCircle,
  mdiArrowRight,
  mdiArrowLeft,
  mdiPaletteSwatch,
  mdiCheck,
  mdiTableOfContents,
  mdiFormatHeaderPound,
  mdiDotsGrid,
  mdiApplicationImport,
  mdiApplicationExport,
  mdiPageLayoutHeader,
  mdiFormatQuoteClose,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiMinus,
  mdiFileTree,
  mdiBug,
  mdiTagRemove,
  mdiFormatLetterCaseLower,
  mdiFormatLetterCaseUpper,
  mdiFormatLetterCase,
  mdiMagnify,
  mdiPlaylistStar,
  mdiSetMerge,
  mdiPlaylistEdit,
  mdiDotsHorizontal,
  mdiDotsVertical,
  mdiTableHeadersEye,
  mdiPageLayoutHeaderFooter,
  mdiTableColumn,
  mdiFormatAlignLeft,
  mdiTableMergeCells,
  mdiTablePlus,
  mdiTableArrowLeft,
  mdiTableArrowRight,
  mdiTableMinus,
  mdiTableCheck,
  mdiTableColumnWidth,
  mdiTableSync,
  mdiTableRow,
  mdiTooltipPlusOutline,
  mdiTooltipMinusOutline,
  mdiPageLayoutBody,
  mdiPageLayoutFooter,
  mdiTableRowPlusBefore,
  mdiTableRowPlusAfter,
  mdiTableRowRemove,
  mdiTableColumnRemove,
  mdiTableColumnPlusAfter,
  mdiTableColumnPlusBefore,
  mdiFormatColumns,
  mdiFormatAlignCenter,
  mdiFormatAlignRight,
  mdiFormatAlignMiddle,
  mdiFormatAlignTop,
  mdiFormatAlignBottom,
  mdiArrowCollapseHorizontal,
  mdiArrowExpandHorizontal,
  mdiArrowCollapseVertical,
  mdiArrowExpandVertical,
  mdiTableSplitCell,
  mdiRegex,
  mdiCancel,
  mdiTextSearch,
  mdiContentSave,
  mdiPencilLock,
  mdiCursorPointer,
  mdiFindReplace,
  mdiFilterOutline,
  mdiAutorenew,
  mdiChevronDoubleRight,
  mdiFileExport,
  mdiFileImport,
  mdiImageOutline,
  mdiArrowExpand,
  mdiNotePlus,
  mdiCloseBoxMultipleOutline,
  mdiRefresh,
  mdiCloseBoxMultiple,
  mdiArrowExpandAll,
  mdiFileDocument,
  mdiCloseCircleOutline,
  mdiFolder,
  mdiFolderOpen,
  mdiMenuRight,
  mdiBookmarkPlus,
  mdiCommentBookmark,
  mdiBookmarkRemove,
  mdiContentSaveAlert,
  mdiWindowMaximize,
  mdiWindowMinimize,
  mdiWindowClose,
  mdiFileQuestion,
  mdiOpenInApp,
  mdiArrowLeftRight,
  mdiCodeTags,
  mdiExpandAll,
  mdiCollapseAll,
  mdiContentSaveEdit,
  mdiContentCopy,
  mdiContentPaste,
  mdiContentCut,
  mdiFileReplaceOutline,
  mdiOctagram,
  mdiTextBoxPlus,
  mdiInvoiceListOutline,
  mdiFolderPlus,
  mdiHelpCircleOutline,
  mdiNoteRemove,
  mdiTagPlus,
  mdiWrapDisabled,
  mdiPencil,
  mdiBookPlay,
  mdiDebugStepInto,
  mdiMessageReplyOutline,
  mdiNumeric10BoxOutline,
  mdiDatabaseSearch,
  mdiFileImage,
  mdiFormatItalic,
  mdiFormatBold,
  mdiFormatUnderline,
  mdiFormatStrikethrough,
  mdiFormatSubscript,
  mdiFormatSuperscript,
  mdiSquareRoot,
  mdiLink,
  mdiBookAccount,
  mdiLanguageC,
  mdiLocationExit,
  mdiLocationEnter,
  mdiSwapHorizontal,
  mdiSelectPlace,
  mdiSquareRounded,
  mdiArrowCollapseDown,
  mdiArrowCollapseUp,
  mdiArrowTopRight,
  mdiArrowBottomRight,
  mdiAlphaDCircleOutline,
  mdiFormatListText,
  mdiAlphaTBoxOutline,
  mdiAlphaDBoxOutline,
  mdiPlaylistPlus,
  mdiAlphaPBoxOutline,
  mdiFormatListGroup,
  mdiCodeBraces,
  mdiImageFrame,
  mdiImageText,
  mdiBookAlphabet,
  mdiTagTextOutline,
  mdiMapMarkerOutline,
  mdiNote,
  mdiAlphaMBox,
  mdiCheckboxMarkedCircle,
  mdiAlphaSCircle,
  mdiFormatAlignJustify,
  mdiAlphaICircle,
  mdiAlphaBCircle,
  mdiSquareRoundedOutline,
  mdiContentDuplicate,
  mdiSelect,
  mdiBookArrowDown,
} from '@quasar/extras/mdi-v7';

import {
  commonIcons,
  NODE_NAME_BLOCKQUOTE,
  NODE_NAME_BULLET_LIST,
  NODE_NAME_CODE_BLOCK,
  NODE_NAME_DEFINITION_DATA,
  NODE_NAME_DEFINITION_LIST,
  NODE_NAME_DEFINITION_TERM,
  NODE_NAME_DIV,
  NODE_NAME_EMPTY_SPAN,
  NODE_NAME_FIGURE,
  NODE_NAME_FIGURE_CAPTION,
  NODE_NAME_HORIZONTAL_RULE,
  NODE_NAME_IMAGE,
  NODE_NAME_INDEX_DIV,
  NODE_NAME_INDEX_TERM,
  NODE_NAME_LINE,
  NODE_NAME_LINE_BLOCK,
  NODE_NAME_LIST_ITEM,
  NODE_NAME_META_BLOCKS,
  NODE_NAME_META_BOOL,
  NODE_NAME_META_INLINES,
  NODE_NAME_META_LIST,
  NODE_NAME_META_MAP,
  NODE_NAME_META_STRING,
  NODE_NAME_METADATA,
  NODE_NAME_NOTE,
  NODE_NAME_ORDERED_LIST,
  NODE_NAME_PANDOC_TABLE,
  NODE_NAME_PARAGRAPH,
  NODE_NAME_PLAIN,
  NODE_NAME_RAW_BLOCK,
  NODE_NAME_RAW_INLINE,
  NODE_NAME_SHORT_CAPTION
} from '../../common';

export const icons: Record<string, string> = {
  ...commonIcons,
  add: mdiPlus,
  add_document: mdiFileDocumentPlus,
  add_action: mdiPlus,
  alert_circle: mdiAlertCircle,
  align_default: mdiFormatColumns,
  align_left: mdiFormatAlignLeft,
  align_center: mdiFormatAlignCenter,
  align_right: mdiFormatAlignRight,
  align_top: mdiFormatAlignTop,
  align_bottom: mdiFormatAlignBottom,
  align_middle: mdiFormatAlignMiddle,
  alternative_set: mdiNumeric10BoxOutline,
  arrow_upward: mdiArrowUp,
  arrow_downward: mdiArrowDown,
  arrow_drop_down: mdiMenuDown,
  arrow_left: mdiArrowLeft,
  arrow_right: mdiArrowRight,
  arrow_left_right: mdiArrowLeftRight,
  arrow_bottom: mdiArrowCollapseDown,
  arrow_bottom_right: mdiArrowBottomRight,
  arrow_top: mdiArrowCollapseUp,
  arrow_top_right: mdiArrowTopRight,
  attributes: mdiPlaylistEdit,
  attributes_add: mdiPlus,
  attributes_edit: mdiPlaylistEdit,
  attributes_suggestions: mdiDotsHorizontal,
  attributes_values: mdiDotsVertical,
  block: mdiSquareRounded,
  block_move: mdiSwapVertical,
  block_convert: mdiSwapHorizontal,
  bookmark_add: mdiBookmarkPlus,
  bookmark_edit: mdiCommentBookmark,
  bookmark_remove: mdiBookmarkRemove,
  bulletlist: mdiFormatListBulleted,
  cancel: mdiCancel,
  caption: mdiPageLayoutHeader,
  caption_add: mdiTooltipPlusOutline,
  caption_delete: mdiTooltipMinusOutline,
  case_to_lower: mdiFormatLetterCaseLower,
  case_to_upper: mdiFormatLetterCaseUpper,
  case_to_upperfirst: mdiFormatLetterCase,
  check: mdiCheck,
  chevron_left: mdiChevronLeft,
  chevron_right: mdiChevronRight,
  cite: mdiBookAccount,
  classes: mdiOctagram,
  classes_add: mdiOctagramPlus,
  clipboard_copy: mdiContentCopy,
  clipboard_cut: mdiContentCut,
  clipboard_paste: mdiContentPaste,
  close: mdiClose,
  code: mdiLanguageC,
  collapse: mdiCollapseAll,
  collapse_vertical: mdiArrowCollapseVertical,
  custom_blocks: mdiPaletteSwatch,
  custom_classes_add: mdiOctagramPlusOutline,
  document_go_to_line: mdiDebugStepInto,
  document_new: mdiFileDocument,
  document_open: mdiFolderOpen,
  document_open_in_main_editor: mdiOpenInApp,
  document_question: mdiFileQuestion,
  document_render: mdiBookPlay,
  document_save: mdiContentSave,
  document_save_as: mdiContentSaveEdit,
  document_save_copy: mdiContentSavePlus,
  document_transform: mdiFileReplaceOutline,
  debug: mdiBug,
  delete: mdiTrashCan,
  drag_handle: mdiDotsGrid,
  duplicate: mdiContentDuplicate,
  edit: mdiPencil,
  emph: mdiFormatItalic,
  expand: mdiExpandAll,
  expand_vertical: mdiArrowExpandVertical,
  export: mdiFileExport,
  figure_wrap: mdiApplicationImport,
  figure_unwrap: mdiApplicationExport,
  file_pdf_box: mdiFilePdfBox,
  filter: mdiFilterOutline,
  first_page: mdiPageFirst,
  folder: mdiFolder,
  folder_new: mdiFolderPlus,
  header_style: mdiFormatHeaderPound,
  horizontal_rule: mdiMinus,
  image_file: mdiFileImage,
  import: mdiFileImport,
  index: mdiCursorPointer,
  index_auto_id: mdiDatabaseSearch,
  index_ref: mdiCursorPointer,
  index_propagate_name: mdiBookArrowDown,
  indices: mdiCursorPointer,
  image_check: mdiImageCheck,
  image_check_outline: mdiImageCheckOutline,
  insert_unicode_char: mdiAlphaCCircleOutline,
  last_page: mdiPageLast,
  link: mdiLink,
  list_view: mdiViewList,
  load_predefined: mdiPlaylistStar,
  marks_add: mdiTagPlus,
  marks_remove: mdiTagRemove,
  marks_clear: mdiTagRemove,
  marks_merge: mdiSetMerge,
  math: mdiSquareRoot,
  menu_down: mdiMenuDown,
  menu_right: mdiMenuRight,
  metadata_custom: mdiHelpCircleOutline,
  metamap_edit_key: mdiPencil,
  node_unknown: mdiSquareRoundedOutline,
  note_expand: mdiArrowExpand,
  note_to_text: mdiNoteRemove,
  notes_close_all: mdiCloseBoxMultiple,
  notes_close_all_of_type: mdiCloseBoxMultipleOutline,
  notes_expand_all: mdiArrowExpandAll,
  notes_expand_all_of_type: mdiArrowExpand,
  note_refresh_all: mdiRefresh,
  note_add: mdiNotePlus,
  orderedlist: mdiFormatListNumbered,
  page_first: mdiPageFirst,
  page_left: mdiChevronLeft,
  page_right: mdiChevronRight,
  page_last: mdiPageLast,
  place_of_insertion: mdiSelectPlace,
  play_arrow: mdiPlay,
  project_structure: mdiFileTree,
  raw_block: mdiAlertCircle,
  raw_inline: mdiCodeTags,
  root_document: mdiFileStarFourPoints,
  redo: mdiRedo,
  regex: mdiRegex,
  reload: mdiReload,
  reload_with_other_configuration: mdiSyncCircle,
  remove_class: mdiOctagramMinus,
  remove_custom_class: mdiOctagramMinusOutline,
  remove_item: mdiCloseCircleOutline,
  render: mdiBookCog,
  repeat_command: mdiRepeatVariant,
  result_message: mdiMessageReplyOutline,
  save: mdiContentSave,
  search: mdiMagnify,
  search_text: mdiTextSearch,
  search_cycle: mdiFindReplace,
  search_case_insensitive: mdiFormatLetterCase,
  search_filter: mdiFilterOutline,
  search_replace: mdiAutorenew,
  search_next: mdiChevronRight,
  search_prev: mdiChevronLeft,
  search_next_all: mdiChevronDoubleRight,
  search_only: mdiPencilLock,
  select: mdiSelect,
  span_edit: mdiPlaylistEdit,
  span_set: mdiTextBoxPlus,
  span_alternatives: mdiInvoiceListOutline,
  strikeout: mdiFormatStrikethrough,
  strong: mdiFormatBold,
  subscript: mdiFormatSubscript,
  summary: mdiTableOfContents,
  superscript: mdiFormatSuperscript,
  swap_blocks: mdiSwapVertical,
  table: mdiTable,
  table_align_controls: mdiFormatAlignLeft,
  table_body: mdiPageLayoutBody,
  table_body_headers_controls: mdiTableHeadersEye,
  table_cell_colspan_decrease: mdiArrowCollapseHorizontal,
  table_cell_colspan_increase: mdiArrowExpandHorizontal,
  table_cell_rowspan_decrease: mdiArrowCollapseVertical,
  table_cell_rowspan_increase: mdiArrowExpandVertical,
  table_cell_split: mdiTableSplitCell,
  table_cells_merge: mdiTableMergeCells,
  table_cells_controls: mdiTableMergeCells,
  table_check_and_fix: mdiTableCheck,
  table_column: mdiTableColumn,
  table_column_add_after: mdiTableColumnPlusAfter,
  table_column_add_before: mdiTableColumnPlusBefore,
  table_column_delete: mdiTableColumnRemove,
  table_format_column: mdiFormatColumns,
  table_controls: mdiTable,
  table_delete: mdiTableMinus,
  table_foot: mdiPageLayoutFooter,
  table_from_text: mdiTableArrowLeft,
  table_full_width: mdiTableColumnWidth,
  table_head: mdiPageLayoutHeader,
  table_new: mdiTablePlus,
  table_row: mdiTableRow,
  table_row_add_after: mdiTableRowPlusAfter,
  table_row_add_before: mdiTableRowPlusBefore,
  table_row_delete: mdiTableRowRemove,
  table_rows_cols_controls: mdiTableColumn,
  table_section_delete: mdiTrashCan,
  table_sections_controls: mdiPageLayoutHeaderFooter,
  table_style: mdiTable,
  table_sync: mdiTableSync,
  table_to_text: mdiTableArrowRight,
  tabular_view: mdiTable,
  toggle_plain: mdiFormatParagraph,
  underline: mdiFormatUnderline,
  undo: mdiUndo,
  unsaved_content: mdiContentSaveAlert,
  // unwrap: mdiWrapDisabled,
  unwrap: mdiLocationExit,
  warning: mdiAlertCircle,
  window_maximize: mdiWindowMaximize,
  window_minimize: mdiWindowMinimize,
  window_close: mdiWindowClose,
  wrap: mdiLocationEnter,
  zoom_out: mdiMinus,
  zoom_in: mdiPlus,
  [NODE_NAME_PARAGRAPH]: mdiFormatParagraph,
  [NODE_NAME_DIV]: mdiAlphaDCircleOutline,
  [NODE_NAME_DEFINITION_LIST]: mdiFormatListText,
  [NODE_NAME_DEFINITION_TERM]: mdiAlphaTBoxOutline,
  [NODE_NAME_DEFINITION_DATA]: mdiAlphaDBoxOutline,
  [NODE_NAME_BULLET_LIST]: mdiFormatListBulleted,
  [NODE_NAME_ORDERED_LIST]: mdiFormatListNumbered,
  [NODE_NAME_LIST_ITEM]: mdiPlaylistPlus,
  [NODE_NAME_HORIZONTAL_RULE]: mdiMinus,
  [NODE_NAME_RAW_BLOCK]: mdiCodeTags,
  [NODE_NAME_PLAIN]: mdiAlphaPBoxOutline,
  [NODE_NAME_LINE_BLOCK]: mdiFormatListGroup,
  [NODE_NAME_LINE]: mdiPlaylistPlus,
  [NODE_NAME_CODE_BLOCK]: mdiCodeBraces,
  [NODE_NAME_BLOCKQUOTE]: mdiFormatQuoteClose,
  [NODE_NAME_PANDOC_TABLE]: mdiTable,
  [NODE_NAME_FIGURE]: mdiImageFrame,
  [NODE_NAME_FIGURE_CAPTION]: mdiImageText,
  [NODE_NAME_SHORT_CAPTION]: mdiTagTextOutline,
  [NODE_NAME_INDEX_TERM]: mdiCursorPointer,
  [NODE_NAME_INDEX_DIV]: mdiBookAlphabet,
  [NODE_NAME_EMPTY_SPAN]: mdiMapMarkerOutline,
  [NODE_NAME_IMAGE]: mdiImageOutline,
  [NODE_NAME_NOTE]: mdiNote,
  [NODE_NAME_RAW_INLINE]: mdiCodeTags,
  [NODE_NAME_METADATA]: mdiAlphaMBox,
  [NODE_NAME_META_BLOCKS]: mdiAlphaBCircle,
  [NODE_NAME_META_INLINES]: mdiAlphaICircle,
  [NODE_NAME_META_MAP]: mdiViewList,
  [NODE_NAME_META_LIST]: mdiFormatAlignJustify,
  [NODE_NAME_META_STRING]: mdiAlphaSCircle,
  [NODE_NAME_META_BOOL]: mdiCheckboxMarkedCircle,
};

export function setupQuasarIcons() {
  const $q = useQuasar();
  $q.iconMapFn = (iconName) => {
    const icon = icons[iconName];
    if (icon !== void 0) {
      return { icon: icon };
    }
  };
}
