import { MARK_NAME_CODE, MARK_NAME_LINK, MARK_NAME_SPAN, NODE_NAME_CODE_BLOCK, NODE_NAME_DIV, NODE_NAME_EMPTY_SPAN, NODE_NAME_FIGURE, NODE_NAME_HEADING, NODE_NAME_IMAGE, NODE_NAME_INDEX_DIV, NODE_NAME_INDEX_REF, NODE_NAME_INDEX_TERM, NODE_NAME_NOTE, NODE_NAME_PANDOC_TABLE, NODE_NAME_PARAGRAPH, NODE_NAME_TABLE_BODY, NODE_NAME_TABLE_CELL, NODE_NAME_TABLE_FOOT, NODE_NAME_TABLE_HEAD, NODE_NAME_TABLE_HEADER, NODE_NAME_TABLE_ROW } from "../prosemirrorNames";

export const HasPandocAttr: Record<string, string> = {
  [MARK_NAME_SPAN]: 'Span',
  [NODE_NAME_PANDOC_TABLE]: 'Table',
  [NODE_NAME_TABLE_HEAD]: 'TableHead',
  [NODE_NAME_TABLE_BODY]: 'TableBody',
  [NODE_NAME_TABLE_FOOT]: 'TableFoot',
  [NODE_NAME_TABLE_ROW]: 'Row',
  [NODE_NAME_TABLE_CELL]: 'Cell',
  [NODE_NAME_TABLE_HEADER]: 'header Cell',
  [NODE_NAME_HEADING]: 'Header',
  [NODE_NAME_DIV]: 'Div',
  [NODE_NAME_FIGURE]: 'Figure',
  [MARK_NAME_LINK]: 'Link',
  [NODE_NAME_IMAGE]: 'Image',
  [NODE_NAME_CODE_BLOCK]: 'CodeBlock',
  [MARK_NAME_CODE]: 'Code',
  [NODE_NAME_INDEX_DIV]: 'IndexDiv',
  [NODE_NAME_INDEX_TERM]: 'IndexTerm',
  [NODE_NAME_INDEX_REF]: 'IndexRef',
  [NODE_NAME_EMPTY_SPAN]: 'EmptySpan',
  [NODE_NAME_NOTE]: 'Note',
} as const;
