/**
 * Concise descriptions of Pandoc format extensions, based on the Pandoc
 * User's Guide. Keys are the identifiers returned by `pandoc --list-extensions`.
 */
export const PANDOC_EXTENSION_DESCRIPTIONS: Readonly<Record<string, string>> = {
  abbreviations: 'Recognize abbreviation definitions.',
  alerts: 'Parse GitHub-style alert blocks.',
  all_symbols_escapable: 'Allow every ASCII punctuation character to be escaped.',
  amuse: 'Enable Text::Amuse extensions in Muse input.',
  angle_brackets_escapable: 'Allow angle brackets to be escaped.',
  ascii_identifiers: 'Generate ASCII-only heading identifiers.',
  attributes: 'Parse attributes in Djot input.',
  auto_identifiers: 'Generate identifiers for headings automatically.',
  autolink_bare_uris: 'Turn bare URIs into links automatically.',
  backtick_code_blocks: 'Parse indented backtick code blocks.',
  blank_before_blockquote: 'Require a blank line before block quotes.',
  blank_before_header: 'Require a blank line before headings.',
  bracketed_spans: 'Parse bracketed spans with attributes.',
  citations: 'Parse and write native citations.',
  definition_lists: 'Parse definition lists.',
  element_citations: 'Write JATS references as element-citation elements.',
  east_asian_line_breaks: 'Treat line breaks between East Asian characters as spaces.',
  emoji: 'Parse emoji names such as :smile: as emoji characters.',
  empty_paragraphs: 'Preserve empty paragraphs.',
  escaped_line_breaks: 'Treat a backslash followed by a newline as a hard line break.',
  example_lists: 'Parse example lists with reusable numbering.',
  fancy_lists: 'Support additional ordered-list marker styles.',
  fenced_code_attributes: 'Allow attributes on fenced code blocks.',
  fenced_code_blocks: 'Parse fenced code blocks.',
  fenced_divs: 'Parse fenced div blocks with attributes.',
  footnotes: 'Parse footnotes.',
  four_space_rule: 'Require four spaces to start indented code blocks.',
  gfm_auto_identifiers: 'Generate heading identifiers using GitHub’s algorithm.',
  grid_tables: 'Parse grid tables.',
  gutenberg: 'Recognize Project Gutenberg metadata.',
  hard_line_breaks: 'Treat all newlines as hard line breaks.',
  header_attributes: 'Allow identifiers, classes, and attributes on headings.',
  ignore_line_breaks: 'Treat soft line breaks as spaces.',
  implicit_figures: 'Turn standalone images into figures with captions.',
  implicit_header_references: 'Create links to headings from their text.',
  inline_code_attributes: 'Allow attributes on inline code.',
  inline_notes: 'Parse inline notes.',
  intraword_underscores: 'Allow emphasis markers inside words.',
  latex_macros: 'Parse LaTeX macro definitions and apply them.',
  line_blocks: 'Parse line blocks.',
  link_attributes: 'Allow attributes on links and images.',
  lists_without_preceding_blankline: 'Allow lists without a preceding blank line.',
  literate_haskell: 'Treat the document as literate Haskell source.',
  markdown_attribute: 'Allow Markdown to be specified in HTML attributes.',
  markdown_in_html_blocks: 'Parse Markdown inside HTML block elements.',
  mark: 'Parse highlighted text.',
  mmd_header_identifiers: 'Use MultiMarkdown-style heading identifiers.',
  mmd_link_attributes: 'Allow MultiMarkdown link attributes.',
  mmd_title_block: 'Parse a MultiMarkdown title block.',
  multiline_tables: 'Parse multiline tables.',
  native_divs: 'Parse HTML div elements as native Div blocks.',
  native_numbering: 'Use target-format fields to number figures and tables.',
  native_spans: 'Parse HTML span elements as native Span inlines.',
  ntb: 'Use Natural Tables instead of Extreme Tables in ConTeXt output.',
  old_dashes: 'Parse old-style Markdown dash conventions.',
  pandoc_title_block: 'Parse Pandoc’s legacy title block.',
  pipe_tables: 'Parse pipe tables.',
  raw_attribute: 'Allow raw content with an explicit output format.',
  raw_html: 'Preserve raw HTML not representable in Pandoc’s AST.',
  raw_markdown: 'Preserve notebook Markdown cells as raw Markdown.',
  raw_tex: 'Preserve raw TeX, LaTeX, and ConTeXt content.',
  rebase_relative_paths: 'Rebase relative paths when reading files.',
  shortcut_reference_links: 'Parse shortcut reference links.',
  short_subsuperscripts: 'Allow short superscript and subscript forms.',
  simple_tables: 'Parse simple tables.',
  smart: 'Convert typographic punctuation and common abbreviations.',
  smart_quotes: 'Convert straight quotes to curly quotes in Org.',
  sourcepos: 'Include source-position attributes in output.',
  space_in_atx_header: 'Require a space after ATX heading markers.',
  spaced_reference_links: 'Allow spaces in reference link labels.',
  special_strings: 'Convert dash, hyphen, and ellipsis sequences in Org.',
  startnum: 'Preserve explicit ordered-list starting numbers.',
  strikeout: 'Parse strikethrough text.',
  styles: 'Preserve custom DOCX styles as attributes.',
  subscript: 'Parse subscript text.',
  superscript: 'Parse superscript text.',
  table_attributes: 'Allow attributes on tables.',
  table_captions: 'Allow captions on tables.',
  tagging: 'Produce ConTeXt markup suitable for tagged PDFs.',
  task_lists: 'Parse task-list items.',
  tex_math_dollars: 'Parse TeX math delimited by dollar signs.',
  tex_math_double_backslash: 'Parse TeX math delimited by double backslashes.',
  tex_math_gfm: 'Parse GitHub-Flavored Markdown TeX math.',
  tex_math_single_backslash: 'Parse TeX math delimited by single backslashes.',
  wikilinks_title_after_pipe: 'Interpret text after a wiki-link pipe as its title.',
  xrefs_name: 'Write ODT cross-references using referenced names or captions.',
  xrefs_number: 'Write ODT cross-references using referenced numbers.',
  yaml_metadata_block: 'Parse a YAML metadata block.',
}
