export const SK_REPEAT_COMMAND = 'Alt-r';
export const SK_MOVE_NODE_UP = 'Alt-ArrowUp';
export const SK_MOVE_NODE_DOWN = 'Alt-ArrowDown';

export const SK_SET_LINEBREAK = 'Mod-Enter';
export const SK_SET_LINEBREAK_ALT = 'Shift-Enter';
export const SK_SET_SOFTBREAK = 'Alt-Enter';
export const SK_TOGGLE_STRIKEOUT = 'Mod-Shift-x';
export const SK_WRAP_IN_FIGURE = 'Mod-Shift-f';
export const SK_TOGGLE_PLAIN = 'Mod-Alt-p';
export const SK_BREAK_PLAIN = 'Enter';
export const SK_CONVERT_TO_RAWBLOCK = 'Alt-Shift-w';
export const SK_TOGGLE_RAWINLINE = 'Alt-w';
export const SK_TOGGLE_DIV = 'Mod-Shift-d';
export const SK_TOGGLE_LINK = 'Mod-l';
export const SK_INSERT_ANCHOR = 'Alt-l';
export const SK_EDIT_ATTRIBUTES = 'Alt-a';

// from tiptap
export const SK_UNDO = 'Mod-z';
export const SK_REDO = 'Shift-Mod-z';
export const SK_REDO_ALT = 'Mod-y';
// Mod-Alt-${level} = heading of level
export const SK_TOGGLE_PARAGRAPH = 'Mod-Alt-0';
export const SK_TOGGLE_EMPH = 'Mod-i';
export const SK_TOGGLE_EMPH_ALT = 'Mod-I';
export const SK_TOGGLE_BOLD = 'Mod-b';
export const SK_TOGGLE_BOLD_ALT = 'Mod-B';
export const SK_TOGGLE_UNDERLINE = 'Mod-u';
export const SK_TOGGLE_UNDERLINE_ALT = 'Mod-U';
export const SK_TOGGLE_SUPERSCRIPT = 'Mod-.';
export const SK_TOGGLE_SUBSCRIPT = 'Mod-,';
// export const SK_TOGGLE_STRIKEOUT = "Mod-Shift-s" // used for save-as
export const SK_TOGGLE_SMALLCAPS = 'Mod-k';
export const SK_TOGGLE_CODE = 'Mod-e';
export const SK_TOGGLE_SPAN = 'Mod-Shift-Space';
export const SK_TOGGLE_HIGHLIGHT = 'Mod-Shift-h';
export const SK_TOGGLE_SINGLEQUOTE = "Mod-Shift-'";
export const SK_TOGGLE_DOUBLEQUOTE = 'Mod-Shift-2';
export const SK_TOGGLE_MATH = 'Mod-Shift-m';
export const SK_ALIGN_LEFT = 'Mod-Shift-l';
export const SK_ALIGN_CENTER = 'Mod-Shift-e';
export const SK_ALIGN_RIGHT = 'Mod-Shift-r';
export const SK_ALIGN_JUSTIFY = 'Mod-Shift-j';
export const SK_TOGGLE_BLOCKQUOTE = 'Mod-Shift-b';
export const SK_TOGGLE_CODEBLOCK = 'Mod-Alt-c';
export const SK_TOGGLE_ORDEREDLIST = 'Mod-Shift-7';
export const SK_TOGGLE_BULLETLIST = 'Mod-Shift-8';
